ignite:
  configuration:
    main:
      peerClassLoadingEnabled: true
      includeEventTypes:
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 63
        - 64
        - 65
    finder:
      addresses:
        - 127.0.0.1:47500
        - 127.0.0.1:47501
        - 127.0.0.1:47502
